### ISSUE TITLE
Mix  Launchers and applications not working for Qt Apps under Wayland (Plasma 6)

### ISSUE THREAD

**Issue by ArArgyridis** [dkondor/cairo-dock-core#12]
It seems that for Qt Applications "Mix Applications with Launchers" not working under Wayland (at least in Plasma 6), instead they appear independently at the end of the dock (or as defined in the "Place new icons" option). 

I tried the following applications (may apply to others):
- Dolphin
- Kate
- QGIS
- QtCreator

And performed the following experiments:
- Wayland + cairo-dock -L -o --> issue
- Wayland + cairo-dock -c  --> issue
- X11 + cairo-dock -c -->no issue

I remember that you cannot test on Plasma 6, so feel free to tell me if I can assist you in any way :-)

p.s. Cairo-Dock works fine on my laptop with hybrid graphics, still haven't tried the latest version on my Desktop to check the other reported issue

**Comment by dkondor** [comment]
Hi,

this is very likely caused by the app-id (sent as an identifier of the window) does not match the corresponding .desktop file (the filename of its launcher stored in `/usr/share/applications`). I've already seen many issues with apps not setting this correctly (and we have added an increasing number of workarounds and I've been considering to rewrite this part completely).

What would be really helpful if you could find out the app-id set by the application and the name of its .desktop file (I can give more detailed info how to do this over the weekend when I have a bit more time). This would allow me to improve the related code.

As a workaround, you can try setting the app-id manually, the option for that is "Class of the program" if you right click on its launcher and select "Edit". Or you can click "Grab" and then click on an open window of the app.
![image](https://github.com/dkondor/cairo-dock-core/assets/6224679/31204451-d93f-48cb-889d-fbcb4c7f6f5f)

**Comment by ArArgyridis** [comment]
The workaround for it indeed works. I can help you with the classes, when you have time tell me what to do exactly and how I can send you the info.

**Comment by dkondor** [comment]
I was able to reproduce this, as it does not actually depend on running on Plasma (just I don't use any of the apps affected normally). I have an idea how to fix it and will let you know once I have a tentative fix.

**Comment by dkondor** [comment]
I pushed a fix in this branch: https://github.com/dkondor/cairo-dock-core/commits/alt_class/
Let me know if this fixes the problem for you as well -- I'll also do some more testing.

**Comment by ArArgyridis** [comment]
I just tried the fix. 
- With my current settings there is no indicator at all on the apps and there is no way to see them
- With new settings it seems working with the default theme, however if the theme changes then again the apps are present independently. Of course if I set the class on the launcher it works as you suggested before.

**Comment by dkondor** [comment]
Thank you for the quick feedback!
> I just tried the fix.
> 
>     * With my current settings there is no indicator at all on the apps and there is no way to see them
Do you mean the dots that show under apps that have windows open? Which theme are you using? Also, are you using a HiDPI display? (scale factor > 1) I had some issues before with such indicators not rendered properly, but only tested with the default theme (where I was able to fix it).
> 
>     * With new settings it seems working with the default theme, however if the theme changes then again the apps are present independently. Of course if I set the class on the launcher it works as you suggested before.
I also found related issues when adding new launchers, so it seems I need to think more carefully about this. I'll test more with changing themes as well.

**Comment by ArArgyridis** [comment]
> Do you mean the dots that show under apps that have windows open? Which theme are you using?

I am using the MacOSX Theme, a bit customized though. This theme uses an arrow to indicate that there are applications running

> Also, are you using a HiDPI display? (scale factor > 1)

On my laptop where I did the test no, but please keep in mind that this issue appeared with the latest update that I used, before everything was working OK.

>  I also found related issues when adding new launchers, so it seems I need to think more carefully about this.

I am no expert at all on how these applications and APIs work, but I was wondering if there is *somewhere* where each application registers the program class and you can make a match between the .desktop and the class. Or maybe one idea could be to check on the code used for example by KDE's task manager or other similar applets from other desktops and see how they handle it

**Comment by dkondor** [comment]
Thank you, I tried the OSX theme and see multiple further issues as well, so I'll try to follow up on them. There is a way in which apps are matched to their desktop files, but the current implementation is based on how things work on X11, and it will need adjustments in more places than I originally thought :)

**Comment by ArArgyridis** [comment]
Don't adjustments follow that rule always :P. In any case let me know if I can contribute to this somehow, I have experience with c++ (and some in pure c) but I am not familiar at all with how these libraries work

**Comment by dkondor** [comment]
Hi,
I have a second attempt here that works in the cases I could test so far, including changing themes:
https://github.com/dkondor/cairo-dock-core/tree/alt_class
It would be great if you could test again

**Comment by dkondor** [comment]
> With my current settings there is no indicator at all on the apps and there is no way to see them

I think this is an issue with the theme and least when newly switching to it I see that it includes an absolute path for such indicators:
![image](https://github.com/dkondor/cairo-dock-core/assets/6224679/19a3b31a-5760-463f-9eb2-07d1f2e1d509)
If I change the setting here, it works for me. I've changed the code to load a default indicator if it fails to find the one from the theme, but this might not look very nice depending on the theme.

**Comment by ArArgyridis** [comment]
Everything works normally now! I think we can close this.

**Comment by dkondor** [comment]
Thanks, I have merged the changes
