### ISSUE TITLE
latest cairo-dock-plug-ins can't be compile on archlinux any more

### ISSUE THREAD

**Issue by ssfdust** [dkondor/cairo-dock-core#13]
This [commit](https://github.com/dkondor/cairo-dock-plug-ins/commit/b5dad7364ac30a01c1fb42f4e3c3152c08840a4b) results in CDApplet.c can't be found any more.
related link: https://aur.archlinux.org/packages/cairo-dock-plug-ins-wayland-git#comment-964560

**Comment by dkondor** [comment]
Hi,
thanks for reporting -- yes, it seems the last commit was in error, I'll revert it.

**Comment by ssfdust** [comment]
Thanks!
