### ISSUE TITLE
Cairo dock does not start

### ISSUE THREAD

**Issue by janekgithubek** [dkondor/cairo-dock-core#15]
Hi, 

On the the commits from last days cairo-dock does not start, last working commit was from 15 September. Error message that I got:

Cairo-Dock version: 3.5.99.beta1
   compiled date: Sep 23 2024 14:47:19

Cairo-Dock was built with support for:
 * GTK version:                  3.24
 * X11:                          yes
 * Wayland:                      yes
 * GLX:                          yes
 * EGL:                          yes
 * gtk-layer-shell:              yes
 * additional Wayland protocols: yes
 * Wayfire IPC:                  no

Cairo-Dock is currently running with:
 * display backend:              Wayland
 * layer-shell:                  yes
 * OpenGL:                       EGL
 * taskbar backend:              plasma
 * desktop manager backend(s):   plasma-window-management; plasma-virtual-desktop
 * detected desktop environment: KDE
 ============================================================================

warning :  (/home/user/RPM/BUILD/cairo-dock-core-wayland_new/src/cairo-dock.c:main:773)  
  showing the maintenance mode ...
warning :  (/home/user/RPM/BUILD/cairo-dock-core-wayland_new/src/cairo-dock.c:main:775)  
  end of the maintenance mode.
g_file_test: assertion 'filename != NULL' failed
g_file_test: assertion 'filename != NULL' failed
warning :  (/home/user/RPM/BUILD/cairo-dock-core-wayland_new/src/cairo-dock.c:_cairo_dock_intercept_signal:189)  
  Cairo-Dock has crashed (sig 11).
It will be restarted now.
Feel free to report this bug on glx-dock.org to help improving the dock!

**Comment by dkondor** [comment]
Hi,
thank you for testing! Commit 700d702d7571676e1e65b16f3e1fd29427cae8ee introduced an issue that would result in a crash under some cases. This is fixed by commit 3c9b8dfdffdac7e8c715a78f0e8772a0365c681b (so it is fixed in the latest master branch); could you confirm that this is not the case?

**Comment by janekgithubek** [comment]
Hi, 
The error message that was posted yesterday was on the newest commit https://github.com/dkondor/cairo-dock-core/tree/29496132400ef6203570ee61018d8c2bab7e9edd

Error message on commit suggested by you https://github.com/dkondor/cairo-dock-core/commit/3c9b8dfdffdac7e8c715a78f0e8772a0365c681b

Cairo-Dock version: 3.5.99.beta1
   compiled date: Sep 24 2024 10:45:27

Cairo-Dock was built with support for:
 * GTK version:                  3.24
 * X11:                          yes
 * Wayland:                      yes
 * GLX:                          yes
 * EGL:                          yes
 * gtk-layer-shell:              yes
 * additional Wayland protocols: yes
 * Wayfire IPC:                  no

Cairo-Dock is currently running with:
 * display backend:              Wayland
 * layer-shell:                  yes
 * OpenGL:                       EGL
 * taskbar backend:              plasma
 * desktop manager backend(s):   plasma-window-management; plasma-virtual-desktop
 * detected desktop environment: KDE
 ============================================================================


warning :  (/home/user/RPM/BUILD/cairo-dock-core-wayland_new/src/cairo-dock.c:main:773)  
  showing the maintenance mode ...
gdk_x11_window_get_xid: assertion 'GDK_IS_X11_WINDOW (window)' failed
warning :  (/home/user/RPM/BUILD/cairo-dock-core-wayland_new/src/cairo-dock.c:main:775)  
  end of the maintenance mode.
g_file_test: assertion 'filename != NULL' failed
g_file_test: assertion 'filename != NULL' failed
warning :  (/home/user/RPM/BUILD/cairo-dock-core-wayland_new/src/cairo-dock.c:_cairo_dock_intercept_signal:189)  
  Cairo-Dock has crashed (sig 11).
It will be restarted now.
Feel free to report this bug on glx-dock.org to help improving the dock!

**Comment by dkondor** [comment]
Thank you, I see. Unfortunately, I cannot reproduce it so far, so I would like to ask your help with providing more info:
 - Are you using KDE plasma as your desktop environment? If yes, which version?
 - Are any apps running when you try starting Cairo-Dock?
 - Do you try to run it with OpenGL enabled / disabled (`cairo-dock -c`)?
 - Was it working well before the latest update?

It would be great if you could provide a backtrace, because the output does not show anything very specific. You would need gdb for it, and run from a terminal:
```
gdb cairo-dock
run -T
```
wait until it crashes (answer 'n' if it asks about downloading additional debug info) and then:
```
bt
```
and copy the full output from there. It would help a lot figuring out the issue!

**Comment by janekgithubek** [comment]
Hi,

Tests were performed on latest master

Are you using KDE plasma as your desktop environment? If yes, which version?
      KDE Plasma 6.1.5
    
Are any apps running when you try starting Cairo-Dock?
      I have tried without any other apps, the same result
    
Do you try to run it with OpenGL enabled / disabled (cairo-dock -c)?
     Yes, the same result.

Was it working well before the latest update?
    It is still working on https://github.com/dkondor/cairo-dock-core/tree/bc9db67f0f806319061676f7ef57f83906153f21
I have recompiled it once again to be sure, and it is still working fine.

The requested debug info:

(gdb) run -T
Starting program: /usr/bin/cairo-dock -T

Enable debuginfod for this session? (y or [n]) n
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff42006c0 (LWP 39194)]
[New Thread 0x7ffff38006c0 (LWP 39195)]
[New Thread 0x7ffff2e006c0 (LWP 39196)]
[New Thread 0x7ffff24006c0 (LWP 39197)]
[New Thread 0x7ffff1a006c0 (LWP 39198)]
[New Thread 0x7ffff10006c0 (LWP 39199)]
[Thread 0x7ffff10006c0 (LWP 39199) exited]
[New Thread 0x7fffe9a006c0 (LWP 39200)]
[New Thread 0x7fffe90006c0 (LWP 39201)]
[New Thread 0x7fffdfe006c0 (LWP 39202)]
[New Thread 0x7fffdf4006c0 (LWP 39203)]
[New Thread 0x7fffdea006c0 (LWP 39204)]
[New Thread 0x7fffde0006c0 (LWP 39205)]
EGL version: 1;5
[New Thread 0x7fffdd6006c0 (LWP 39206)]
[New Thread 0x7fffdcc006c0 (LWP 39207)]
[New Thread 0x7fffd3e006c0 (LWP 39208)]

 ============================================================================
Cairo-Dock version: 3.5.99.beta1
   compiled date: Sep 25 2024 07:39:32

Cairo-Dock was built with support for:
 * GTK version:                  3.24
 * X11:                          yes
 * Wayland:                      yes
 * GLX:                          yes
 * EGL:                          yes
 * gtk-layer-shell:              yes
 * additional Wayland protocols: yes
 * Wayfire IPC:                  no

Cairo-Dock is currently running with:
 * display backend:              Wayland
 * layer-shell:                  yes
 * OpenGL:                       EGL
 * taskbar backend:              plasma
 * desktop manager backend(s):   plasma-window-management; plasma-virtual-desktop
 * detected desktop environment: KDE
 ============================================================================

[New Thread 0x7fffd34006c0 (LWP 39209)]
[New Thread 0x7fffd2a006c0 (LWP 39210)]
[New Thread 0x7fffd20006c0 (LWP 39211)]
g_file_test: assertion 'filename != NULL' failed
g_file_test: assertion 'filename != NULL' failed

Thread 1 "cairo-dock" received signal SIGSEGV, Segmentation fault.
0x00007ffff5b8d01a in __strcmp_sse42 () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff5b8d01a in __strcmp_sse42 () at /lib64/libc.so.6
#1  0x00007ffff64ec646 in cairo_dock_register_class_full () at /lib64/libgldi.so.3
#2  0x00007ffff64aab53 in _get_launcher_params () at /lib64/libgldi.so.3
#3  0x00007ffff64aae78 in init_object () at /lib64/libgldi.so.3
#4  0x00007ffff649c4f5 in gldi_object_init () at /lib64/libgldi.so.3
#5  0x00007ffff649c613 in gldi_object_new () at /lib64/libgldi.so.3
#6  0x00007ffff64ad100 in _user_icon_create () at /lib64/libgldi.so.3
#7  0x00007ffff64ad18a in _load_one_icon () at /lib64/libgldi.so.3
#8  0x00007ffff73a9d62 in g_ptr_array_foreach () at /lib64/libglib-2.0.so.0
#9  0x00007ffff64ad4bb in gldi_user_icons_new_from_directory () at /lib64/libgldi.so.3
#10 0x00007ffff651f4aa in cairo_dock_load_current_theme () at /lib64/libgldi.so.3
#11 0x0000000000412c1b in main ()

**Comment by dkondor** [comment]
Thanks, I think I found the issue -- could you test with the latest master? (commit 389135f94925e0c1de4bfeaf36440476f8e69381)

**Comment by janekgithubek** [comment]
Hi,

It is working again! Thank you very much!!
