### ISSUE TITLE
The trash-bin plugin cause cairo-dock to crash

### ISSUE THREAD

**Issue by ssfdust** [dkondor/cairo-dock-core#8]
### steps to reproduce
1. Enable bin plugin in Files catagroy.
2. Start a file manager which supports trash-bin, e.g. thunar
3. Delete a file in file manager
4. The dock crashes

**Comment by ssfdust** [comment]
I found the problem, the dock will crash when `~/.config/gtk-3.0/bookmarks` is not empty.

**Comment by dkondor** [comment]
Thank you for reporting! Just to clarify, does this only happen with thunar? Also do you have the xfce-integration or the gnome-integration plugin active? I cannot reproduce so far, but I would like to investigate more (I've looked at the PR and I suspect that the problem originates elsewhere).

**Comment by ssfdust** [comment]
It doesn't only happen with thunar, but also happens with trash-cli. I try to trace cairo-dock with gdb, and find that the global myDock is null pointer, which seems abnormal.
I don't enable any integration plugin, maybe that's the problem. I am using wayfire on archlinux, do you have any advice?

**Comment by dkondor** [comment]
This sounds quite strange, and my feeling is that there is a memory corruption bug somewhere else. I will need some more time to try to reproduce so I can try to find the source of the problem. In the meantime, you could try maybe:
 - run the dock with adding the option `-e gnome`  -- does the problem still occur?
 - Also, just to be sure, does this only happen on Wayland? (I don't see anything related to X11 in the trashbin code
Thank you!

**Comment by ssfdust** [comment]
> run the dock with adding the option -e gnome -- does the problem still occur?

It still occurs when the dock starts with `-e gnome` option

> Also, just to be sure, does this only happen on Wayland? (I don't see anything related to X11 in the trashbin code

No, it doesn't only happen on wayland, but also happens on X11, cairo mode and opengl mode.

**Comment by ssfdust** [comment]
I think I really need my ugly patch...

**Comment by dkondor** [comment]
I was able to reproduce this and I think I found the cause of the problem (in the shortcuts plugin as you said). The following patch for the plug-ins fixes things for me:
https://github.com/dkondor/cairo-dock-plug-ins/pull/2
(without the need for #9 )
It would be great if you could confirm this as well

**Comment by ssfdust** [comment]
I applied the patch without #9, but it still crashes in `ic->prev`.

### Backtrace
```
#0  cairo_dock_calculate_wave_with_position_linear (pIconList=pIconList@entry=0x7fff8c02ddc0 = {...}, x_abs=<optimized out>, fMagnitude=<optimized out>, fFlatDockWidth=fFlatDockWidth@entry=342, iWidth=iWidth@entry=0x0, iHeight=iHeight@entry=0x0, fAlign=fAlign@entry=0.5, fFoldingFactor=fFoldingFactor@entry=0, bDirectionUp=0x1) at /usr/src/debug/cairo-dock-core-wayland-git/cairo-dock-core-wayland-git/src/gldit/cairo-dock-dock-facility.c:745
#1  0x00007ffff72adcc0 in cairo_dock_calculate_max_dock_width (pDock=pDock@entry=0x55555586a630, fFlatDockWidth=342, fWidthConstraintFactor=fWidthConstraintFactor@entry=1, fExtraWidth=fExtraWidth@entry=61) at /usr/src/debug/cairo-dock-core-wayland-git/cairo-dock-core-wayland-git/src/gldit/cairo-dock-dock-facility.c:586
#2  0x00007ffff72f7030 in cd_calculate_max_dock_size_default (pDock=0x55555586a630) at /usr/src/debug/cairo-dock-core-wayland-git/cairo-dock-core-wayland-git/src/implementations/cairo-dock-default-view.c:55
#3  0x00007ffff72af3a1 in cairo_dock_update_dock_size (pDock=0x55555586a630) at /usr/src/debug/cairo-dock-core-wayland-git/cairo-dock-core-wayland-git/src/gldit/cairo-dock-dock-facility.c:86
#4  cairo_dock_update_dock_size (pDock=0x55555586a630) at /usr/src/debug/cairo-dock-core-wayland-git/cairo-dock-core-wayland-git/src/gldit/cairo-dock-dock-facility.c:49
#5  0x00007ffff72af8f8 in _update_dock_size_idle (pDock=0x55555586a630) at /usr/src/debug/cairo-dock-core-wayland-git/cairo-dock-core-wayland-git/src/gldit/cairo-dock-dock-facility.c:192
#6  0x00007ffff7dd3f69 in g_main_dispatch (context=0x5555555e3c40) at ../glib/glib/gmain.c:3476
#7  0x00007ffff7e32367 in g_main_context_dispatch_unlocked (context=0x5555555e3c40) at ../glib/glib/gmain.c:4284
#8  g_main_context_iterate_unlocked.isra.0 (context=0x5555555e3c40, block=block@entry=0x1, dispatch=dispatch@entry=0x1, self=<optimized out>) at ../glib/glib/gmain.c:4349
#9  0x00007ffff7dd4b97 in g_main_loop_run (loop=0x555555bd8330) at ../glib/glib/gmain.c:4551
#10 0x00007ffff76262df in gtk_main () at ../gtk/gtk/gtkmain.c:1329
#11 0x00005555555602f2 in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/cairo-dock-core-wayland-git/cairo-dock-core-wayland-git/src/cairo-dock.c:951

```

**Comment by dkondor** [comment]
Thanks, this is interesting. Can you share which plugins you have enabled?
(It should be in the main config file: )

Also, does the trash appear among the bookmarks, e.g. in the left side
panel in Thunar?

**Comment by dkondor** [comment]
Never mind, I think I found the problem and we do need #9 -- I'll merge 
after some more testing. Thanks for testing!

**Comment by dkondor** [comment]
I've updated https://github.com/dkondor/cairo-dock-plug-ins/pull/2
and again I think #9 should not be needed -- but let me know if you see any more problems

**Comment by ssfdust** [comment]
I have followed the latest patch, the dock doesn't crash any more.
Thank you very much!
